# Generated by Django 5.1.4 on 2025-01-14 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("post", "0004_bookmarks_comments_alter_posts_likes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Like", "Like"),
                            ("Comment", "Comment"),
                            ("Bookmark", "Bookmark"),
                        ],
                        max_length=100,
                        verbose_name="Type of the notification",
                    ),
                ),
                (
                    "is_seen",
                    models.BooleanField(
                        default=False, verbose_name="If the notification is seen or not"
                    ),
                ),
                (
                    "arrived_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="The arrival date of the notification",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="post.posts",
                        verbose_name="Post at which the notification is made",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User who received the notification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-arrived_at"],
            },
        ),
    ]
