# Generated by Django 5.1.4 on 2025-01-14 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="notifications",
            table="Notifications",
        ),
    ]
