[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"
watchPatterns = [
    "requirements.txt",
    "railway.toml",
    "Dockerfile",
    "pyproject.toml",
    "*",
]
# add a list of ignored files
ignorePatterns = [".env", ".venv", "__pycache__"]
