# Generated by Django 5.1.4 on 2025-01-13 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "userProfile",
            "0002_alter_userprofile_address_alter_userprofile_author_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="Title of the category"
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="category_images",
                        verbose_name="image of the category",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="slug of the category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "db_table": "Categories",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Title of the post"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description of the post"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Draft", "Draft"),
                            ("Disabled", "Disabled"),
                        ],
                        default="Active",
                        verbose_name="Current Status of the post",
                    ),
                ),
                (
                    "views",
                    models.IntegerField(
                        default=0, verbose_name="No of views of the post"
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="post_images",
                        verbose_name="image of the post",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="slug of the post",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="The creation date of the post"
                    ),
                ),
                (
                    "updated_at",
                    models.DateField(
                        auto_now=True, verbose_name="Updated date of the post"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts_category",
                        to="post.category",
                        verbose_name="Category of the post",
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="likes_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Users who liked the post",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts_profile",
                        to="userProfile.userprofile",
                        verbose_name="Profile details of the post creator user",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The Creator of the post",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Posts",
                "db_table": "Posts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "category"], name="Posts_user_id_47af68_idx"
                    ),
                    models.Index(
                        fields=["user", "profile"], name="Posts_user_id_e1b7ce_idx"
                    ),
                ],
            },
        ),
    ]
