# Generated by Django 5.1.4 on 2025-01-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Updated date of the post"
            ),
        ),
    ]
