# Generated by Django 5.1.4 on 2025-01-13 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0003_alter_posts_category_alter_posts_profile_and_more"),
        ("userProfile", "0003_alter_userprofile_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookmarks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bookmarked_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="The creation date of the bookmark",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Bookmarks",
                "db_table": "Bookmarks",
                "ordering": ["-bookmarked_at"],
            },
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.TextField(verbose_name="Actual comment text on the post"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="The creation date of the comment",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Updated date of the comment"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="Slug of the comment",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Comments",
                "db_table": "Comments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="posts",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="likes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Users who liked the post",
            ),
        ),
        migrations.AddIndex(
            model_name="posts",
            index=models.Index(
                fields=["user", "status"], name="Posts_user_id_24a115_idx"
            ),
        ),
        migrations.AddField(
            model_name="bookmarks",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to="post.posts",
                verbose_name="Post at which the bookmark is made",
            ),
        ),
        migrations.AddField(
            model_name="bookmarks",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User who added the bookmark",
            ),
        ),
        migrations.AddField(
            model_name="comments",
            name="in_reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="post.comments",
                verbose_name="Reply to this comment",
            ),
        ),
        migrations.AddField(
            model_name="comments",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="post.posts",
                verbose_name="Post at which the comment is made",
            ),
        ),
        migrations.AddField(
            model_name="comments",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User who made the comment",
            ),
        ),
        migrations.AddIndex(
            model_name="bookmarks",
            index=models.Index(
                fields=["user", "post"], name="Bookmarks_user_id_12b971_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comments",
            index=models.Index(
                fields=["user", "post"], name="Comments_user_id_e9d8b0_idx"
            ),
        ),
    ]
