# Generated by Django 5.1.4 on 2025-01-14 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0004_bookmarks_comments_alter_posts_likes_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookmarks",
            options={
                "ordering": ["-bookmarked_at"],
                "verbose_name": "Bookmark",
                "verbose_name_plural": "Bookmarks",
            },
        ),
        migrations.AlterModelOptions(
            name="posts",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
        ),
    ]
