# Generated by Django 5.1.4 on 2025-01-14 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userProfile", "0003_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "ordering": ["-jone_date"],
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.AlterModelTable(
            name="userprofile",
            table="UserProfiles",
        ),
    ]
